---
# tasks file for server
- name: Update yum cache
  yum: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  yum: name={{ item }} state=present
  become: yes
  with_items:
    - epel-release
    - httpd
    - mysql-community-server
    - php7.2-mysql
    - php7.2
    - libapache2-mod-php7.2
    - python-mysqldb
